In [42]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Lets create a dataset first, from individual datasets from the seasons 2010 and onwards:

In [43]:
with open('data/col_keys.txt') as file:
    col_key_text = file.readlines()

col_key = {}
for line in col_key_text:
    splits = line.split(' = ')
    col_key[splits[0]] = splits[1].rstrip()
col_key

{'Div': 'League Division',
 'Date': 'Match Date (dd/mm/yy)',
 'HomeTeam': 'Home Team',
 'AwayTeam': 'Away Team',
 'FTHG': 'Full Time Home Team Goals',
 'HG': 'Full Time Home Team Goals',
 'FTAG': 'Full Time Away Team Goals',
 'AG': 'Full Time Away Team Goals',
 'FTR': 'Full Time Result (H=Home Win, D=Draw, A=Away Win)',
 'Res': 'Full Time Result (H=Home Win, D=Draw, A=Away Win)',
 'HTHG': 'Half Time Home Team Goals',
 'HTAG': 'Half Time Away Team Goals',
 'HTR': 'Half Time Result (H=Home Win, D=Draw, A=Away Win)',
 'Attendance': 'Crowd Attendance',
 'Referee': 'Match Referee',
 'HS': 'Home Team Shots',
 'AS': 'Away Team Shots',
 'HST': 'Home Team Shots on Target',
 'AST': 'Away Team Shots on Target',
 'HHW': 'Home Team Hit Woodwork',
 'AHW': 'Away Team Hit Woodwork',
 'HC': 'Home Team Corners',
 'AC': 'Away Team Corners',
 'HF': 'Home Team Fouls Committed',
 'AF': 'Away Team Fouls Committed',
 'HFKC': 'Home Team Free Kicks Conceded',
 'AFKC': 'Away Team Free Kicks Conceded',
 'HO': 'Home Team Offsides',
 'AO': 'Away Team Offsides',
 'HY': 'Home Team Yellow Cards',
 'AY': 'Away Team Yellow Cards',
 'HR': 'Home Team Red Cards',
 'AR': 'Away Team Red Cards',
 'HBP': 'Home Team Bookings Points (10',
 'ABP': 'Away Team Bookings Points (10',
 'B365H': 'Bet365 home win odds',
 'B365D': 'Bet365 draw odds',
 'B365A': 'Bet365 away win odds',
 'BSH': 'Blue Square home win odds',
 'BSD': 'Blue Square draw odds',
 'BSA': 'Blue Square away win odds',
 'BWH': 'Bet&Win home win odds',
 'BWD': 'Bet&Win draw odds',
 'BWA': 'Bet&Win away win odds',
 'GBH': 'Gamebookers home win odds',
 'GBD': 'Gamebookers draw odds',
 'GBA': 'Gamebookers away win odds',
 'IWH': 'Interwetten home win odds',
 'IWD': 'Interwetten draw odds',
 'IWA': 'Interwetten away win odds',
 'LBH': 'Ladbrokes home win odds',
 'LBD': 'Ladbrokes draw odds',
 'LBA': 'Ladbrokes away win odds',
 'PSH': 'Pinnacle home win odds',
 'PH': 'Pinnacle home win odds',
 'PSD': 'Pinnacle draw odds',
 'PD': 'Pinnacle draw odds',
 'PSA': 'Pinnacle away win odds',
 'PA': 'Pinnacle away win odds',
 'SOH': 'Sporting Odds home win odds',
 'SOD': 'Sporting Odds draw odds',
 'SOA': 'Sporting Odds away win odds',
 'SBH': 'Sportingbet home win odds',
 'SBD': 'Sportingbet draw odds',
 'SBA': 'Sportingbet away win odds',
 'SJH': 'Stan James home win odds',
 'SJD': 'Stan James draw odds',
 'SJA': 'Stan James away win odds',
 'SYH': 'Stanleybet home win odds',
 'SYD': 'Stanleybet draw odds',
 'SYA': 'Stanleybet away win odds',
 'VCH': 'VC Bet home win odds',
 'VCD': 'VC Bet draw odds',
 'VCA': 'VC Bet away win odds',
 'WHH': 'William Hill home win odds',
 'WHD': 'William Hill draw odds',
 'WHA': 'William Hill away win odds',
 'Bb1X2': 'Number of BetBrain bookmakers used to calculate match odds averages and maximums',
 'BbMxH': 'Betbrain maximum home win odds',
 'BbAvH': 'Betbrain average home win odds',
 'BbMxD': 'Betbrain maximum draw odds',
 'BbAvD': 'Betbrain average draw win odds',
 'BbMxA': 'Betbrain maximum away win odds',
 'BbAvA': 'Betbrain average away win odds',
 'MaxH': 'Oddsportal maximum home win odds',
 'MaxD': 'Oddsportal maximum draw win odds',
 'MaxA': 'Oddsportal maximum away win odds',
 'AvgH': 'Oddsportal average home win odds',
 'AvgD': 'Oddsportal average draw win odds',
 'AvgA': 'Oddsportal average away win odds',
 'BbOU': 'Number of BetBrain bookmakers used to calculate over/under 2.5 goals (total goals) averages and maximums',
 'BbMx>2.5': 'Betbrain maximum over 2.5 goals',
 'BbAv>2.5': 'Betbrain average over 2.5 goals',
 'BbMx<2.5': 'Betbrain maximum under 2.5 goals',
 'BbAv<2.5': 'Betbrain average under 2.5 goals',
 'GB>2.5': 'Gamebookers over 2.5 goals',
 'GB<2.5': 'Gamebookers under 2.5 goals',
 'B365>2.5': 'Bet365 over 2.5 goals',
 'B365<2.5': 'Bet365 under 2.5 goals',
 'P>2.5': 'Pinnacle over 2.5 goals',
 'P<2.5': 'Pinnacle under 2.5 goals',
 'Max>2.5': 'Oddsportal maximum over 2.5 goals',
 'Max<2.5': 'Oddsportal maximum under 2.5 goals',
 'Avg>2.5': 'Oddsportal average over 2.5 goals',
 'Avg<2.5': 'Oddsportal average under 2.5 goals',
 'BbAH': 'Number of BetBrain bookmakers used to Asian handicap averages and maximums',
 'BbAHh': 'Betbrain size of handicap (home team)',
 'AHh': 'Oddsportal size of handicap (home team) (since 2019/2020)',
 'BbMxAHH': 'Betbrain maximum Asian handicap home team odds',
 'BbAvAHH': 'Betbrain average Asian handicap home team odds',
 'BbMxAHA': 'Betbrain maximum Asian handicap away team odds',
 'BbAvAHA': 'Betbrain average Asian handicap away team odds',
 'GBAHH': 'Gamebookers Asian handicap home team odds',
 'GBAHA': 'Gamebookers Asian handicap away team odds',
 'GBAH': 'Gamebookers size of handicap (home team)',
 'LBAHH': 'Ladbrokes Asian handicap home team odds',
 'LBAHA': 'Ladbrokes Asian handicap away team odds',
 'LBAH': 'Ladbrokes size of handicap (home team)',
 'B365AHH': 'Bet365 Asian handicap home team odds',
 'B365AHA': 'Bet365 Asian handicap away team odds',
 'B365AH': 'Bet365 size of handicap (home team)',
 'PAHH': 'Pinnacle Asian handicap home team odds',
 'PAHA': 'Pinnacle Asian handicap away team odds',
 'MaxAHH': 'Oddsportal maximum Asian handicap home team odds',
 'MaxAHA': 'Oddsportal maximum Asian handicap away team odds',
 'AvgAHH': 'Oddsportal average Asian handicap home team odds',
 'AvgAHA': 'Oddsportal average Asian handicap away team odds'}

In [44]:
data_2010 = pd.read_csv('data/2010_11.csv')
data_2011 = pd.read_csv('data/2011_12.csv')
data_2012 = pd.read_csv('data/2012_13.csv')
data_2013 = pd.read_csv('data/2013_14.csv')
data_2014 = pd.read_csv('data/2014_15.csv')
data_2015 = pd.read_csv('data/2015_16.csv')
data_2016 = pd.read_csv('data/2016_17.csv')
data_2017 = pd.read_csv('data/2017_18.csv')
data_2018 = pd.read_csv('data/2018_19.csv')

In [45]:
data_2010['Season'] = '2010/2011'
data_2011['Season'] = '2011/2012'
data_2012['Season'] = '2012/2013'
data_2013['Season'] = '2013/2014'
data_2014['Season'] = '2014/2015'
data_2015['Season'] = '2015/2016'
data_2016['Season'] = '2016/2017'
data_2017['Season'] = '2017/2018'
data_2018['Season'] = '2018/2019'

In [46]:
dataframes = [data_2010, data_2011, data_2012, data_2013, data_2014, data_2015, data_2016, data_2017, data_2018]
data = pd.concat(dataframes, axis=0, sort=False)
data.head(10)

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAvAHH,BbMxAHA,BbAvAHA,Season,PSH,PSD,PSA,PSCH,PSCD,PSCA
0,E0,14/08/10,Aston Villa,West Ham,3.0,0.0,H,2.0,0.0,H,...,1.40,3.00,2.78,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
1,E0,14/08/10,Blackburn,Everton,1.0,0.0,H,1.0,0.0,H,...,2.05,1.85,1.75,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
2,E0,14/08/10,Bolton,Fulham,0.0,0.0,D,0.0,0.0,D,...,1.55,2.56,2.36,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
3,E0,14/08/10,Chelsea,West Brom,6.0,0.0,H,2.0,0.0,H,...,2.01,1.91,1.85,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
4,E0,14/08/10,Sunderland,Birmingham,2.0,2.0,D,1.0,0.0,H,...,1.55,2.50,2.38,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
5,E0,14/08/10,Tottenham,Man City,0.0,0.0,D,0.0,0.0,D,...,1.69,2.28,2.12,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
6,E0,14/08/10,Wigan,Blackpool,0.0,4.0,A,0.0,3.0,A,...,1.32,3.75,3.19,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
7,E0,14/08/10,Wolves,Stoke,2.0,1.0,H,2.0,0.0,H,...,1.63,2.40,2.20,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
8,E0,15/08/10,Liverpool,Arsenal,1.0,1.0,D,0.0,0.0,D,...,1.74,2.15,2.06,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN
9,E0,16/08/10,Man United,Newcastle,3.0,0.0,H,2.0,0.0,H,...,1.03,12.00,10.02,2010/2011,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
data.astype(str).loc[data.HomeTeam == 'nan']

,Div,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,BbAvAHH,BbMxAHA,BbAvAHA,Season,PSH,PSD,PSA,PSCH,PSCD,PSCA
380,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,...,nan,nan,nan,2014/2015,nan,nan,nan,nan,nan,nan

In [83]:
np.unique(data.Div.astype)

TypeError: '<' not supported between instances of 'str' and 'float'

In [47]:
data.to_csv('data/2010-19.csv')

In [56]:
results = pd.read_csv('data/tables_1968_2019.csv')
seasons_to_include = ['2010/2011', '2011/2012', '2012/2013', '2013/2014', '2014/2015', '2015/2016', '2016/2017', '2017/2018', '2018/2019', ]
results = results.loc[results.season.isin(seasons_to_include)]
results.head(10)

,season,name,pos,team,p,w,d,l,f,a,gd,points
0,2018/2019,Premier League 2018-2019,1,Manchester City,38,32,2,4,95,23,72,98
1,2018/2019,Premier League 2018-2019,2,Liverpool,38,30,7,1,89,22,67,97
2,2018/2019,Premier League 2018-2019,3,Chelsea,38,21,9,8,63,39,24,72
3,2018/2019,Premier League 2018-2019,4,Tottenham Hotspur,38,23,2,13,67,39,28,71
4,2018/2019,Premier League 2018-2019,5,Arsenal,38,21,7,10,73,51,22,70
5,2018/2019,Premier League 2018-2019,6,Manchester United,38,19,9,10,65,54,11,66
6,2018/2019,Premier League 2018-2019,7,Wolverhampton Wanderers,38,16,9,13,47,46,1,57
7,2018/2019,Premier League 2018-2019,8,Everton,38,15,9,14,54,46,8,54
8,2018/2019,Premier League 2018-2019,9,Leicester City,38,15,7,16,51,48,3,52
9,2018/2019,Premier League 2018-2019,10,West Ham,38,15,7,16,52,55,-3,52

In [70]:
for (team1, team2) in zip(np.unique(data['HomeTeam'].astype(str)), np.unique(results['team'])):
    print(team1, '  -  ', team2)

Arsenal   -   Arsenal
Aston Villa   -   Aston Villa
Birmingham   -   Birmingham City
Blackburn   -   Blackburn Rovers
Blackpool   -   Blackpool
Bolton   -   Bolton Wanderers
Bournemouth   -   Bournemouth
Brighton   -   Brighton
Burnley   -   Burnley
Cardiff   -   Cardiff City
Chelsea   -   Chelsea
Crystal Palace   -   Crystal Palace
Everton   -   Everton
Fulham   -   Fulham
Huddersfield   -   Huddersfield Town
Hull   -   Hull City
Leicester   -   Leicester City
Liverpool   -   Liverpool
Man City   -   Manchester City
Man United   -   Manchester United
Middlesbrough   -   Middlesbrough
Newcastle   -   Newcastle United
Norwich   -   Norwich City
QPR   -   Queens Park Rangers
Reading   -   Reading
Southampton   -   Southampton
Stoke   -   Stoke City
Sunderland   -   Sunderland
Swansea   -   Swansea City
Tottenham   -   Tottenham Hotspur
Watford   -   Watford
West Brom   -   West Bromwich Albion
West Ham   -   West Ham
Wigan   -   West Ham United
Wolves   -   Wigan
nan   -   Wolverhampton Wanderers

In [55]:
results.to_csv('data/table_2010-19.csv')